add compile step

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -13,27 +13,61 @@ jobs:
                         - name: Prepare environment
                           shell: bash
                           run: |
-                                sudo apt-get update --quiet;
-                                sudo apt-get install --yes --no-install-recommends dkms kmod
+                                  sudo apt-get update --quiet;
+                                  sudo apt-get install --yes --no-install-recommends dkms kmod
 
                         - name: Download header files
                           shell: bash
                           run: |
-                                # latest generic and oem kernel headers
-                                # too old, still 5.4 - sudo apt install linux-headers-generic
-                                sudo apt install linux-headers-oem-20.04
-                                # wip kernel headers
-                                sudo add-apt-repository ppa:canonical-kernel-team/unstable
-                                sudo apt update
-                                sudo apt install linux-headers-generic-wip
+                                  # latest generic kernel headers - once we move to 22.04
+                                  # sudo apt install linux-headers-generic
+                                  # latest oem kernel
+                                  sudo apt install linux-headers-oem-20.04
+                                  # wip kernel headers - once we move to 22.04
+                                  # sudo add-apt-repository ppa:canonical-kernel-team/unstable
+                                  # sudo apt update
+                                  # sudo apt install linux-headers-generic-wip
 
                         - name: Patch build scripts
                           shell: bash
                           run: |
-                                # there is a dependency on the ivsc modules that prevents building the sensor drivers
-                                # remove sensors from the dkms file
-                                sed -i '/\[[4,5,6,7]\]/d' dkms.conf
-                                # disable sensor modules in the Makefile
-                                sed -i 's/export CONFIG_VIDEO_OV/#export CONFIG_VIDEO_OV/g' Makefile
-                                sed -i 's/export CONFIG_VIDEO_HM/#export CONFIG_VIDEO_HM/g' Makefile
+                                  # there is a dependency on the ivsc modules that prevents building the sensor drivers
+                                  # remove sensors from the dkms file
+                                  sed -i '/\[[4,5,6,7]\]/d' dkms.conf
+                                  # disable sensor modules in the Makefile
+                                  sed -i 's/export CONFIG_VIDEO_OV/#export CONFIG_VIDEO_OV/g' Makefile
+                                  sed -i 's/export CONFIG_VIDEO_HM/#export CONFIG_VIDEO_HM/g' Makefile
+
+                        - name: Register w/ dkms
+                          shell: bash
+                          run: |
+                                  sudo dkms add .
+
+                        - name: Compile driver
+                          shell: bash
+                          run: |
+                                  # run dkms build and all available kernel headers
+                                  failed=""
+                                  succeeded=""
+                                  for kver in /lib/modules/*/build; do
+                                        test -d $kver || continue
+                                        kver=${kver%/build}
+                                        kver=${kver##*/}
+                                        echo "=== Testing ${kver} ===";
+                                        echo "running: dkms build -m ipu6-drivers/0.0.0 -k ${kver}";
+                                        ret=$(dkms build -m ipu6-drivers/0.0.0 -k ${kver} >&2; echo $?);
+                                        if [ ${ret} -eq 0 ]; then
+                                                succeeded="${succeeded} ${kver}"
+                                                #modinfo v4l2loopback.ko;
+                                        else
+                                                echo "#### Skipped unexpected failure ${kver}";
+                                                failed="${failed} ${kver}";
+                                        fi;
+                                        #make KERNELRELEASE="${kver}" clean || test ${ret} -ne 0
+                                done
+                                if [ "x${failed}" != "x" ]; then
+                                        echo "#### Failed kernels: ${failed}";
+                                        exit 1
+                                fi
+                                echo "#### Successful builds for kernels: ${succeeded}";
 
